version: "3.9"

services:
  server:
    build: ./server
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - PORT=${SERVER_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  pgdata:
